package Tests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class KisehirarasuuyokTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("https://flights-app.pages.dev/");
    driver.manage().window().maximize();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ikisehirarasuuyok() {

    driver.findElement(By.cssSelector("#headlessui-combobox-button-\\3AR1a9lla\\3A > .h-5")).click();
    driver.findElement(By.cssSelector("#headlessui-combobox-option-\\3Ar0\\3A > .flex")).click();
    driver.findElement(By.cssSelector("#headlessui-combobox-button-\\3AR1ahlla\\3A > .h-5")).click();
    driver.findElement(By.xpath("//li[@id=\'headlessui-combobox-option-:rj:\']/div/span")).click();
    driver.findElement(By.cssSelector(".min-h-screen")).click();
    String expectedMessage = "Bu iki şehir arasında uçuş bulunmuyor. Başka iki şehir seçmeyi deneyebilirsiniz.";
    WebElement messageElement = driver.findElement(By.cssSelector(".mt-24"));
    String actualMessage = messageElement.getText();
    assertEquals(expectedMessage, actualMessage);
    driver.findElement(By.cssSelector("#headlessui-combobox-button-\\3AR1ahlla\\3A > .h-5")).click();
    driver.findElement(By.xpath("//li[@id=\'headlessui-combobox-option-:r14:\']/div/span")).click();
    assertThat(driver.findElement(By.cssSelector(".mb-10")).getText(), is("Found 2 items"));
  }
}
